name: .NET Framework Desktop CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    env:
      Solution_Name: 'VS2022Cleaner.sln' # Nombre de tu solución
      Wap_Project_Directory: 'VS2022Cleaner.Package'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configurar MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # Restaurar paquetes NuGet
    - name: Restore NuGet packages
      run: msbuild -t:restore ${{ env.Solution_Name }}

    # Compilar la solución
    - name: Build the solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=Release /p:Platform="Any CPU"

    # Aquí puedes agregar pasos adicionales para pruebas, firma, empaquetado, etc.

    # Subir artefactos de construcción (ejecutables, DLLs, etc.)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Artifacts
        path: ${{ env.Wap_Project_Directory }}\AppPackages

